"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ru" | "uz";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.works": "Works",
    "nav.demos": "Demos",
    "nav.blog": "Blog",
    "nav.contact": "Contact",

    // Home Page
    "home.tagline1": "Young",
    "home.tagline2": "developers.",
    "home.tagline3": "Big",
    "home.tagline4": "ideas.",
    "home.description": "We are a team of",
    "home.description2": "5 passionate developers",
    "home.description3": "from",
    "home.description4": "Tashkent, Uzbekistan",
    "home.description5": ", creating exceptional websites, games, and mobile applications.",
    "home.description6": "Age 14-21",
    "home.description7": ", united by code.",
    "home.viewWork": "View Our Work",
    "home.getInTouch": "Get in Touch",
    "home.scroll": "Scroll",
    "home.projects": "Projects",
    "home.hackers": "Hackers",
    "home.years": "Years",
    "home.technologies": "Technologies",
    "home.whatWeBuild": "What We Build",
    "home.whatWeBuildDesc": "// High-quality digital products across multiple platforms",
    "home.webDev": "Web Development",
    "home.webDevDesc": "Modern, responsive websites and web applications built with cutting-edge tech.",
    "home.gameDev": "Game Development",
    "home.gameDevDesc": "Immersive gaming experiences for multiple platforms.",
    "home.mobileApps": "Mobile Apps",
    "home.mobileAppsDesc": "Native iOS and Android applications.",
    "home.uiuxDesign": "UI/UX Design",
    "home.uiuxDesignDesc": "Futuristic, intuitive interfaces.",
    "home.networkConnections": "NETWORK CONNECTIONS",
    "home.readyToBuild": "Ready",
    "home.toBuildSomething": "to Build Something",
    "home.amazing": "Amazing",
    "home.ctaDescription": "Let's create the future together. Connect with us today.",
    "home.startProject": "Start a Project",

    // About Page
    "about.terminalPath": "~/about/bi3",
    "about.title": "About",
    "about.subtitle": "The story of five young developers from Tashkent, building the future one line of code at a time.",
    "about.ourStory": "Our Story",
    "about.storyP1": "BI3 was born from a shared passion for technology and creation. We are a team of five developers, aged 14-21, based in Tashkent, Uzbekistan. What started as a group of friends experimenting with code has evolved into a full-fledged development studio.",
    "about.storyP2": "We specialize in web development, game creation, and mobile applications. Our youth is our strength — we bring fresh perspectives, boundless energy, and an insatiable curiosity to every project.",
    "about.storyP3": "As part of the Natex Labs ecosystem and partners with FirstIt, we're committed to pushing the boundaries of what's possible in tech.",
    "about.leadingBi3": "Leading BI3",
    "about.ourValues": "Our Values",
    "about.valuesSubtitle": "// The principles that guide our work",
    "about.innovation": "Innovation",
    "about.innovationDesc": "We embrace new technologies and approaches, always staying ahead of the curve.",
    "about.quality": "Quality",
    "about.qualityDesc": "Every line of code is crafted with care. We don't ship until it's perfect.",
    "about.collaboration": "Collaboration",
    "about.collaborationDesc": "Great things happen when passionate people work together.",
    "about.growth": "Growth",
    "about.growthDesc": "We're always learning, always improving, always evolving.",
    "about.ourPartners": "Our Partners",
    "about.partnersSubtitle": "// Trusted connections in the tech ecosystem",
    "about.location": "Location",
    "about.locationSubtitle": "// Where innovation meets tradition",
    "about.basedIn": "Based in",
    "about.tashkent": "Tashkent, Uzbekistan",
    "about.availableWorldwide": "Available for remote work worldwide",

    // Team Members
    "team.member1.name": "Ibrohim A.",
    "team.member1.role": "CEO & Founder",
    "team.member1.bio": "Visionary leader driving BI3's mission to revolutionize digital development. Passionate about building innovative solutions.",
    "team.member2.name": "Ibrohim R.",
    "team.member2.role": "Project Manager",
    "team.member2.bio": "Orchestrating projects from concept to completion. Expert in agile methodologies and team coordination.",
    "team.member3.name": "Ibrohim U.",
    "team.member3.role": "Front End Developer",
    "team.member3.bio": "Creating stunning user interfaces with modern web technologies. Focused on performance and user experience.",
    "team.member4.name": "Begzod",
    "team.member4.role": "Backend Developer",
    "team.member4.bio": "Building robust server-side solutions and APIs. Expert in database architecture and system design.",
    "team.member5.name": "Ibrohim I.",
    "team.member5.role": "Web3 & Blockchain Developer",
    "team.member5.bio": "Pioneering decentralized solutions and smart contracts. Bringing blockchain innovation to BI3 projects.",
    "team.skill.leadership": "Leadership",
    "team.skill.strategy": "Strategy",
    "team.skill.business": "Business Development",
    "team.skill.agile": "Agile",
    "team.skill.scrum": "Scrum",
    "team.skill.management": "Team Management",
    "team.skill.planning": "Project Planning",
    "team.skill.smartContracts": "Smart Contracts",

    // Services Page
    "services.terminalPath": "~/services",
    "services.title": "Our Services",
    "services.subtitle": "Comprehensive digital solutions from concept to deployment. We bring your ideas to life with cutting-edge technology.",
    "services.webDev": "Web Development",
    "services.webDevDesc": "Modern, responsive, and performant websites and web applications. From landing pages to complex platforms.",
    "services.webDevFeature1": "Custom websites & landing pages",
    "services.webDevFeature2": "Web applications & dashboards",
    "services.webDevFeature3": "E-commerce solutions",
    "services.webDevFeature4": "API development & integration",
    "services.gameDev": "Game Development",
    "services.gameDevDesc": "Engaging games for multiple platforms. From casual mobile games to immersive 3D experiences.",
    "services.gameDevFeature1": "2D & 3D game development",
    "services.gameDevFeature2": "Mobile games (iOS/Android)",
    "services.gameDevFeature3": "PC & browser games",
    "services.gameDevFeature4": "Game design & mechanics",
    "services.mobileDev": "Mobile Development",
    "services.mobileDevDesc": "Native and cross-platform mobile applications that deliver exceptional user experiences.",
    "services.mobileDevFeature1": "iOS app development",
    "services.mobileDevFeature2": "Android app development",
    "services.mobileDevFeature3": "Cross-platform solutions",
    "services.mobileDevFeature4": "App Store optimization",
    "services.uiuxDesign": "UI/UX Design",
    "services.uiuxDesignDesc": "Beautiful, intuitive interfaces that users love. Design that combines aesthetics with functionality.",
    "services.uiuxFeature1": "User interface design",
    "services.uiuxFeature2": "User experience research",
    "services.uiuxFeature3": "Prototyping & wireframing",
    "services.uiuxFeature4": "Design systems",
    "services.ourProcess": "Our Process",
    "services.processSubtitle": "// How we bring your vision to life",
    "services.step1": "Discovery",
    "services.step1Desc": "Understanding your goals, audience, and requirements.",
    "services.step2": "Planning",
    "services.step2Desc": "Detailed roadmap, architecture decisions, and timeline estimation.",
    "services.step3": "Development",
    "services.step3Desc": "Agile development with regular updates and feedback cycles.",
    "services.step4": "Launch",
    "services.step4Desc": "Thorough testing, deployment, and post-launch support.",
    "services.techStack": "Tech Stack",
    "services.techStackSubtitle": "// Technologies we work with",
    "services.readyToStart": "Ready to Start Your Project?",
    "services.ctaDesc": "Let's discuss your ideas and create something amazing together.",
    "services.getInTouch": "Get in Touch",

    // Works Page
    "works.terminalPath": "~/portfolio/works",
    "works.title": "Our Works",
    "works.subtitle": "Explore our portfolio of",
    "works.websites": "websites",
    "works.games": "games",
    "works.mobileApps": "mobile apps",
    "works.designs": "designs",
    "works.weCrafted": "we've crafted.",
    "works.totalProjects": "Total Projects",
    "works.completed": "Completed",
    "works.inProgress": "In Progress",
    "works.comingSoon": "Coming Soon",
    "works.allProjects": "All Projects",
    "works.web": "Web",
    "works.gamesFilter": "Games",
    "works.mobile": "Mobile",
    "works.design": "Design",
    "works.viewLive": "View Live",
    "works.detailsSoon": "[Details Soon]",
    "works.haveProject": "Have a",
    "works.projectInMind": "Project",
    "works.inMind": "in Mind?",
    "works.ctaDesc": "We're always excited to work on new challenges. Let's build something amazing together.",
    "works.startProject": "Start a Project",

    // Demos Page
    "demos.terminalPath": "~/playground/demos",
    "demos.title": "Interactive Demos",
    "demos.subtitle": "Try our",
    "demos.games": "games",
    "demos.webExperiments": "web experiments",
    "demos.prototypes": "interactive prototypes",
    "demos.inBrowser": "right in your browser.",
    "demos.all": "All",
    "demos.gamesFilter": "Games",
    "demos.webFilter": "Web",
    "demos.mobileFilter": "Mobile",
    "demos.experiments": "Experiments",
    "demos.playDemo": "Play Demo",
    "demos.download": "Download",
    "demos.featured": "Featured",
    "demos.fullscreen": "Fullscreen",
    "demos.share": "Share",
    "demos.instantPlay": "Instant Play",
    "demos.instantPlayDesc": "No downloads required. All demos run directly in your browser with WebGL and modern web APIs.",
    "demos.crossPlatform": "Cross-Platform",
    "demos.crossPlatformDesc": "Works on desktop, tablet, and mobile. Responsive controls adapt to your device.",
    "demos.openSource": "Open Source",
    "demos.openSourceDesc": "Many demos are open source. Check our GitHub for source code and learning resources.",

    // Blog Page
    "blog.terminalPath": "~/content/blog",
    "blog.title": "Blog",
    "blog.subtitle": "from the BI3 team.",
    "blog.tutorials": "Tutorials",
    "blog.techInsights": "tech insights",
    "blog.devLogs": "dev logs",
    "blog.news": "news",
    "blog.searchPosts": "Search posts...",
    "blog.allPosts": "All Posts",
    "blog.tech": "Tech",
    "blog.tutorial": "Tutorial",
    "blog.newsFilter": "News",
    "blog.devLog": "Dev Log",
    "blog.featuredPosts": "Featured Posts",
    "blog.latestPosts": "Latest Posts",
    "blog.noPosts": "No posts found.",
    "blog.clearFilters": "Clear filters",
    "blog.stayUpdated": "Stay",
    "blog.updated": "Updated",
    "blog.newsletterDesc": "Subscribe to our newsletter for the latest tutorials, dev logs, and tech insights.",
    "blog.emailPlaceholder": "your@email.com",
    "blog.subscribe": "Subscribe",
    "blog.noSpam": "No spam. Unsubscribe anytime.",
    "blog.minRead": "min read",

    // Contact Page
    "contact.terminalPath": "~/connect/contact",
    "contact.title": "Get in Touch",
    "contact.subtitle": "Have a project in mind? Want to collaborate? Or just want to say hi?",
    "contact.loveToHear": "We'd love to hear from you.",
    "contact.quickContact": "Quick Contact",
    "contact.emailUs": "Email us",
    "contact.telegram": "Telegram",
    "contact.discord": "Discord",
    "contact.community": "BI3 Community",
    "contact.location": "Location",
    "contact.basedIn": "Based in",
    "contact.availableRemote": "Available for remote work worldwide",
    "contact.followUs": "Follow Us",
    "contact.startProject": "Start a Project",
    "contact.formDesc": "Fill out the form below and we'll get back to you within 24 hours.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.projectType": "Project Type",
    "contact.selectType": "Select type...",
    "contact.website": "Website",
    "contact.webApp": "Web Application",
    "contact.mobileApp": "Mobile App",
    "contact.game": "Game",
    "contact.design": "UI/UX Design",
    "contact.other": "Other",
    "contact.budget": "Budget Range",
    "contact.selectBudget": "Select budget...",
    "contact.letsDiscuss": "Let's discuss",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your project...",
    "contact.sendMessage": "Send Message",
    "contact.sending": "Sending...",
    "contact.messageSent": "Message Sent!",
    "contact.thankYou": "Thank you for reaching out. We'll get back to you soon.",
    "contact.sendAnother": "Send Another Message",
    "contact.faq": "Frequently Asked",
    "contact.faq1Q": "What is your typical response time?",
    "contact.faq1A": "We typically respond within 24 hours during business days. For urgent inquiries, reach out via Telegram for faster response.",
    "contact.faq2Q": "Do you work with international clients?",
    "contact.faq2A": "Absolutely! We work with clients worldwide. Our team is experienced in remote collaboration across different time zones.",
    "contact.faq3Q": "What technologies do you specialize in?",
    "contact.faq3A": "We specialize in React/Next.js, Unity/Godot for games, React Native/Flutter for mobile, and modern design tools like Figma.",
    "contact.faq4Q": "How do you handle project pricing?",
    "contact.faq4A": "We offer both fixed-price and hourly arrangements depending on project scope. We'll provide a detailed quote after understanding your requirements.",

    // Footer
    "footer.description": "Young development studio creating exceptional websites, games, and mobile apps from Tashkent, Uzbekistan.",
    "footer.navigation": "Navigation",
    "footer.services": "Services",
    "footer.connect": "Connect",
    "footer.rights": "All rights reserved.",
    "footer.partOf": "Part of",

    // Games Service Page
    "games.title": "Game",
    "games.title2": "Development",
    "games.description": "From concept art to final release, we bring your gaming vision to life.",
    "games.startGame": "Start Your Game",
    "games.playDemos": "Play Our Demos",
    "games.interactiveDemo": "// Interactive Demo - Click to Navigate",
    "games.whatWeCreate": "What We Create",
    "games.whatWeCreateDesc": "// Full-stack game development services",
    "games.pcGames": "PC Games",
    "games.pcGamesDesc": "High-performance games for Windows, Mac, and Linux platforms with stunning graphics.",
    "games.mobileGames": "Mobile Games",
    "games.mobileGamesDesc": "Engaging iOS and Android games optimized for touch controls and mobile performance.",
    "games.browserGames": "Browser Games",
    "games.browserGamesDesc": "WebGL and HTML5 games that run directly in the browser without downloads.",
    "games.3dDev": "3D Development",
    "games.3dDevDesc": "Immersive 3D worlds with realistic physics, lighting, and environments.",
    "games.2dArt": "2D Art & Animation",
    "games.2dArtDesc": "Beautiful 2D graphics, sprite animations, and visual effects.",
    "games.soundMusic": "Sound & Music",
    "games.soundMusicDesc": "Original soundtracks, sound effects, and immersive audio design.",
    "games.gameGenres": "Game Genres",
    "games.gameGenresDesc": "// We develop across all genres",
    "games.techStack": "Tech Stack",
    "games.techStackDesc": "// Industry-standard tools and engines",
    "games.devProcess": "Development Process",
    "games.devProcessDesc": "// From idea to launch",
    "games.concept": "Concept",
    "games.conceptDesc": "Game design document, story, mechanics planning",
    "games.prototype": "Prototype",
    "games.prototypeDesc": "Core gameplay loop, basic mechanics testing",
    "games.production": "Production",
    "games.productionDesc": "Full development, art, sound, polish",
    "games.launch": "Launch",
    "games.launchDesc": "Testing, optimization, release, support",
    "games.readyTo": "Ready to",
    "games.levelUp": "Level Up?",
    "games.ctaDesc": "Let's create an unforgettable gaming experience together.",
    "games.startProject": "Start Project",
    "games.viewGames": "View Our Games",
    "games.action": "Action",
    "games.adventure": "Adventure",
    "games.rpg": "RPG",
    "games.puzzle": "Puzzle",
    "games.platformer": "Platformer",
    "games.shooter": "Shooter",
    "games.strategy": "Strategy",
    "games.simulation": "Simulation",
    "games.racing": "Racing",
    "games.horror": "Horror",
    // Game Menu Demo
    "games.menu.mainMenu": "MAIN MENU",
    "games.menu.selectMode": "SELECT MODE",
    "games.menu.settings": "SETTINGS",
    "games.menu.language": "LANGUAGE",
    "games.menu.play": "PLAY",
    "games.menu.quit": "QUIT",
    "games.menu.singlePlayer": "SINGLE PLAYER",
    "games.menu.playWithFriends": "PLAY WITH FRIENDS",
    "games.menu.back": "BACK",
    "games.menu.graphics": "GRAPHICS",
    "games.menu.audio": "AUDIO",
    "games.menu.controls": "CONTROLS",
    "games.menu.clickToSelect": "CLICK TO SELECT",

    // Web Development Service Page
    "web.title": "Web",
    "web.title2": "Development",
    "web.description": "From concept to deployment, we build modern, scalable web solutions.",
    "web.startProject": "Start Your Project",
    "web.viewWorks": "View Our Works",
    "web.interactiveDemo": "// Interactive Demo - Live Preview",
    "web.whatWeCreate": "What We Build",
    "web.whatWeCreateDesc": "// Full-stack web development services",
    "web.landingPages": "Landing Pages",
    "web.landingPagesDesc": "High-converting landing pages with stunning design and optimal performance.",
    "web.webApps": "Web Applications",
    "web.webAppsDesc": "Complex web applications with rich functionality and seamless user experience.",
    "web.ecommerce": "E-Commerce",
    "web.ecommerceDesc": "Online stores with secure payments, inventory management, and analytics.",
    "web.dashboards": "Dashboards",
    "web.dashboardsDesc": "Data visualization dashboards with real-time updates and interactive charts.",
    "web.apis": "API Development",
    "web.apisDesc": "RESTful and GraphQL APIs with authentication, rate limiting, and documentation.",
    "web.cms": "CMS Solutions",
    "web.cmsDesc": "Custom content management systems tailored to your specific needs.",
    "web.techStack": "Tech Stack",
    "web.techStackDesc": "// Modern technologies we work with",
    "web.frontend": "Frontend",
    "web.backend": "Backend",
    "web.database": "Database",
    "web.devops": "DevOps",
    "web.devProcess": "Development Process",
    "web.devProcessDesc": "// From idea to launch",
    "web.discovery": "Discovery",
    "web.discoveryDesc": "Requirements gathering, user research, project scope",
    "web.design": "Design",
    "web.designDesc": "Wireframes, UI/UX design, prototyping",
    "web.development": "Development",
    "web.developmentDesc": "Frontend, backend, database, testing",
    "web.deployment": "Deployment",
    "web.deploymentDesc": "Launch, monitoring, maintenance, support",
    "web.readyTo": "Ready to",
    "web.goOnline": "Go Online?",
    "web.ctaDesc": "Let's build your digital presence together.",
    "web.startProjectBtn": "Start Project",
    "web.viewPortfolio": "View Portfolio",
    "web.features": "Key Features",
    "web.featuresDesc": "// What makes our websites stand out",
    "web.responsive": "Responsive Design",
    "web.responsiveDesc": "Perfect on all devices - desktop, tablet, and mobile.",
    "web.seo": "SEO Optimized",
    "web.seoDesc": "Built for search engines with best practices and fast loading.",
    "web.secure": "Secure & Reliable",
    "web.secureDesc": "Industry-standard security with SSL, authentication, and data protection.",
    "web.scalable": "Scalable Architecture",
    "web.scalableDesc": "Built to grow with your business needs.",
    "web.fast": "Lightning Fast",
    "web.fastDesc": "Optimized performance with modern caching and CDN.",
    "web.accessible": "Accessible",
    "web.accessibleDesc": "WCAG compliant for users of all abilities.",

    // Mobile Development Service Page
    "mobile.title": "Mobile",
    "mobile.title2": "Development",
    "mobile.description": "Native and cross-platform apps that users love.",
    "mobile.startProject": "Start Your App",
    "mobile.viewApps": "View Our Apps",
    "mobile.interactiveDemo": "// Interactive Demo - Swipe to Navigate",
    "mobile.whatWeCreate": "What We Build",
    "mobile.whatWeCreateDesc": "// Full-cycle mobile development services",
    "mobile.iosApps": "iOS Apps",
    "mobile.iosAppsDesc": "Native Swift apps optimized for iPhone and iPad with Apple's design guidelines.",
    "mobile.androidApps": "Android Apps",
    "mobile.androidAppsDesc": "Native Kotlin apps for the entire Android ecosystem.",
    "mobile.crossPlatform": "Cross-Platform",
    "mobile.crossPlatformDesc": "React Native & Flutter apps that work on both platforms from a single codebase.",
    "mobile.appDesign": "App UI/UX",
    "mobile.appDesignDesc": "Beautiful, intuitive interfaces following platform-specific guidelines.",
    "mobile.backend": "Backend & APIs",
    "mobile.backendDesc": "Scalable server infrastructure and real-time synchronization.",
    "mobile.maintenance": "Maintenance",
    "mobile.maintenanceDesc": "Ongoing updates, bug fixes, and performance optimization.",
    "mobile.techStack": "Tech Stack",
    "mobile.techStackDesc": "// Industry-leading mobile technologies",
    "mobile.ios": "iOS",
    "mobile.android": "Android",
    "mobile.crossPlatformTech": "Cross-Platform",
    "mobile.backendTech": "Backend",
    "mobile.devProcess": "Development Process",
    "mobile.devProcessDesc": "// From concept to App Store",
    "mobile.ideation": "Ideation",
    "mobile.ideationDesc": "Market research, feature planning, technical feasibility",
    "mobile.design": "Design",
    "mobile.designDesc": "Wireframes, prototypes, UI/UX design",
    "mobile.development": "Development",
    "mobile.developmentDesc": "Native/cross-platform coding, API integration",
    "mobile.launch": "Launch",
    "mobile.launchDesc": "Testing, App Store submission, post-launch support",
    "mobile.readyTo": "Ready to",
    "mobile.goMobile": "Go Mobile?",
    "mobile.ctaDesc": "Let's bring your app idea to life.",
    "mobile.startProjectBtn": "Start Project",
    "mobile.viewPortfolio": "View Portfolio",
    "mobile.features": "App Features",
    "mobile.featuresDesc": "// What makes our apps stand out",
    "mobile.offline": "Offline Support",
    "mobile.offlineDesc": "Works seamlessly without internet connection.",
    "mobile.push": "Push Notifications",
    "mobile.pushDesc": "Engage users with timely, relevant notifications.",
    "mobile.analytics": "Analytics",
    "mobile.analyticsDesc": "Track user behavior and app performance.",
    "mobile.security": "Secure",
    "mobile.securityDesc": "Encrypted data, secure authentication, privacy-first.",
    "mobile.performance": "High Performance",
    "mobile.performanceDesc": "Smooth 60fps animations, fast load times.",
    "mobile.updates": "OTA Updates",
    "mobile.updatesDesc": "Push updates without App Store review.",

    // UI/UX Design Service Page
    "design.title": "UI/UX",
    "design.title2": "Design",
    "design.description": "Beautiful, intuitive interfaces that users love.",
    "design.startProject": "Start Your Design",
    "design.viewWorks": "View Our Designs",
    "design.interactiveDemo": "// Interactive Demo - Click to Explore",
    "design.whatWeCreate": "What We Design",
    "design.whatWeCreateDesc": "// End-to-end design services",
    "design.uiDesign": "UI Design",
    "design.uiDesignDesc": "Pixel-perfect interfaces with modern aesthetics and attention to detail.",
    "design.uxResearch": "UX Research",
    "design.uxResearchDesc": "User interviews, surveys, and usability testing to understand your audience.",
    "design.wireframes": "Wireframing",
    "design.wireframesDesc": "Low and high-fidelity wireframes to visualize the user journey.",
    "design.prototyping": "Prototyping",
    "design.prototypingDesc": "Interactive prototypes for testing and stakeholder presentations.",
    "design.designSystems": "Design Systems",
    "design.designSystemsDesc": "Scalable component libraries and style guides for consistency.",
    "design.branding": "Branding",
    "design.brandingDesc": "Logo design, color palettes, typography, and brand identity.",
    "design.tools": "Design Tools",
    "design.toolsDesc": "// Industry-standard software we use",
    "design.designTools": "Design",
    "design.prototypeTools": "Prototyping",
    "design.collaborationTools": "Collaboration",
    "design.devHandoff": "Dev Handoff",
    "design.devProcess": "Design Process",
    "design.devProcessDesc": "// From research to handoff",
    "design.research": "Research",
    "design.researchDesc": "User research, competitor analysis, requirements gathering",
    "design.ideate": "Ideate",
    "design.ideateDesc": "Sketches, wireframes, information architecture",
    "design.designStep": "Design",
    "design.designStepDesc": "Visual design, prototyping, user testing",
    "design.handoff": "Handoff",
    "design.handoffDesc": "Dev specs, assets export, implementation support",
    "design.readyTo": "Ready to",
    "design.standOut": "Stand Out?",
    "design.ctaDesc": "Let's create designs that make an impact.",
    "design.startProjectBtn": "Start Project",
    "design.viewPortfolio": "View Portfolio",
    "design.features": "Design Principles",
    "design.featuresDesc": "// What guides our design decisions",
    "design.userCentered": "User-Centered",
    "design.userCenteredDesc": "Every decision backed by user needs and research.",
    "design.accessible": "Accessible",
    "design.accessibleDesc": "Inclusive design for users of all abilities.",
    "design.consistent": "Consistent",
    "design.consistentDesc": "Unified visual language across all touchpoints.",
    "design.responsive": "Responsive",
    "design.responsiveDesc": "Flawless experience on any screen size.",
    "design.delightful": "Delightful",
    "design.delightfulDesc": "Micro-interactions and animations that engage.",
    "design.scalable": "Scalable",
    "design.scalableDesc": "Design systems that grow with your product.",
  },
  ru: {
    // Navigation
    "nav.home": "Главная",
    "nav.about": "О нас",
    "nav.services": "Услуги",
    "nav.works": "Работы",
    "nav.demos": "Демо",
    "nav.blog": "Блог",
    "nav.contact": "Контакты",

    // Home Page
    "home.tagline1": "Молодые",
    "home.tagline2": "разработчики.",
    "home.tagline3": "Большие",
    "home.tagline4": "идеи.",
    "home.description": "Мы команда из",
    "home.description2": "5 увлечённых разработчиков",
    "home.description3": "из",
    "home.description4": "Ташкента, Узбекистан",
    "home.description5": ", создающих исключительные веб-сайты, игры и мобильные приложения.",
    "home.description6": "Возраст 14-21",
    "home.description7": ", объединённые кодом.",
    "home.viewWork": "Наши работы",
    "home.getInTouch": "Связаться",
    "home.scroll": "Листать",
    "home.projects": "Проектов",
    "home.hackers": "Хакеров",
    "home.years": "Лет",
    "home.technologies": "Технологий",
    "home.whatWeBuild": "Что мы создаём",
    "home.whatWeBuildDesc": "// Качественные цифровые продукты для разных платформ",
    "home.webDev": "Веб-разработка",
    "home.webDevDesc": "Современные, адаптивные сайты и веб-приложения на передовых технологиях.",
    "home.gameDev": "Разработка игр",
    "home.gameDevDesc": "Захватывающие игровые впечатления для разных платформ.",
    "home.mobileApps": "Мобильные приложения",
    "home.mobileAppsDesc": "Нативные приложения для iOS и Android.",
    "home.uiuxDesign": "UI/UX Дизайн",
    "home.uiuxDesignDesc": "Футуристичные, интуитивные интерфейсы.",
    "home.networkConnections": "СЕТЕВЫЕ СВЯЗИ",
    "home.readyToBuild": "Готовы",
    "home.toBuildSomething": "создать что-то",
    "home.amazing": "Потрясающее",
    "home.ctaDescription": "Давайте создадим будущее вместе. Свяжитесь с нами сегодня.",
    "home.startProject": "Начать проект",

    // About Page
    "about.terminalPath": "~/о-нас/bi3",
    "about.title": "О нас",
    "about.subtitle": "История пяти молодых разработчиков из Ташкента, строящих будущее строка за строкой.",
    "about.ourStory": "Наша история",
    "about.storyP1": "BI3 родился из общей страсти к технологиям и созиданию. Мы команда из пяти разработчиков в возрасте 14-21 года из Ташкента, Узбекистан. То, что начиналось как группа друзей, экспериментирующих с кодом, превратилось в полноценную студию разработки.",
    "about.storyP2": "Мы специализируемся на веб-разработке, создании игр и мобильных приложений. Наша молодость — наша сила: мы привносим свежие взгляды, безграничную энергию и неутолимое любопытство в каждый проект.",
    "about.storyP3": "Являясь частью экосистемы Natex Labs и партнёрами FirstIt, мы стремимся раздвигать границы возможного в технологиях.",
    "about.leadingBi3": "Команда BI3",
    "about.ourValues": "Наши ценности",
    "about.valuesSubtitle": "// Принципы, которыми мы руководствуемся",
    "about.innovation": "Инновации",
    "about.innovationDesc": "Мы принимаем новые технологии и подходы, всегда оставаясь впереди.",
    "about.quality": "Качество",
    "about.qualityDesc": "Каждая строка кода создаётся с заботой. Мы не выпускаем, пока не идеально.",
    "about.collaboration": "Сотрудничество",
    "about.collaborationDesc": "Великие вещи случаются, когда увлечённые люди работают вместе.",
    "about.growth": "Рост",
    "about.growthDesc": "Мы всегда учимся, всегда совершенствуемся, всегда развиваемся.",
    "about.ourPartners": "Наши партнёры",
    "about.partnersSubtitle": "// Надёжные связи в tech-экосистеме",
    "about.location": "Локация",
    "about.locationSubtitle": "// Где инновации встречают традиции",
    "about.basedIn": "Расположены в",
    "about.tashkent": "Ташкент, Узбекистан",
    "about.availableWorldwide": "Доступны для удалённой работы по всему миру",

    // Team Members
    "team.member1.name": "Иброхим А.",
    "team.member1.role": "CEO и Основатель",
    "team.member1.bio": "Визионер, ведущий миссию BI3 по революционизации цифровой разработки. Увлечён созданием инновационных решений.",
    "team.member2.name": "Иброхим Р.",
    "team.member2.role": "Проектный Менеджер",
    "team.member2.bio": "Управление проектами от концепции до завершения. Эксперт в agile-методологиях и координации команды.",
    "team.member3.name": "Иброхим У.",
    "team.member3.role": "Front End Разработчик",
    "team.member3.bio": "Создание потрясающих пользовательских интерфейсов с современными веб-технологиями. Фокус на производительности и UX.",
    "team.member4.name": "Бегзод",
    "team.member4.role": "Backend Разработчик",
    "team.member4.bio": "Построение надёжных серверных решений и API. Эксперт в архитектуре баз данных и проектировании систем.",
    "team.member5.name": "Иброхим И.",
    "team.member5.role": "Web3 и Blockchain Разработчик",
    "team.member5.bio": "Пионер децентрализованных решений и смарт-контрактов. Внедрение блокчейн-инноваций в проекты BI3.",
    "team.skill.leadership": "Лидерство",
    "team.skill.strategy": "Стратегия",
    "team.skill.business": "Развитие бизнеса",
    "team.skill.agile": "Agile",
    "team.skill.scrum": "Scrum",
    "team.skill.management": "Управление командой",
    "team.skill.planning": "Планирование проектов",
    "team.skill.smartContracts": "Смарт-контракты",

    // Services Page
    "services.terminalPath": "~/услуги",
    "services.title": "Наши услуги",
    "services.subtitle": "Комплексные цифровые решения от концепции до запуска. Мы воплощаем ваши идеи с помощью передовых технологий.",
    "services.webDev": "Веб-разработка",
    "services.webDevDesc": "Современные, адаптивные и производительные сайты и веб-приложения. От лендингов до сложных платформ.",
    "services.webDevFeature1": "Сайты и лендинги на заказ",
    "services.webDevFeature2": "Веб-приложения и дашборды",
    "services.webDevFeature3": "E-commerce решения",
    "services.webDevFeature4": "Разработка и интеграция API",
    "services.gameDev": "Разработка игр",
    "services.gameDevDesc": "Увлекательные игры для разных платформ. От казуальных мобильных игр до иммерсивных 3D-впечатлений.",
    "services.gameDevFeature1": "2D и 3D игры",
    "services.gameDevFeature2": "Мобильные игры (iOS/Android)",
    "services.gameDevFeature3": "ПК и браузерные игры",
    "services.gameDevFeature4": "Геймдизайн и механики",
    "services.mobileDev": "Мобильная разработка",
    "services.mobileDevDesc": "Нативные и кроссплатформенные мобильные приложения с исключительным пользовательским опытом.",
    "services.mobileDevFeature1": "Разработка для iOS",
    "services.mobileDevFeature2": "Разработка для Android",
    "services.mobileDevFeature3": "Кроссплатформенные решения",
    "services.mobileDevFeature4": "Оптимизация для App Store",
    "services.uiuxDesign": "UI/UX Дизайн",
    "services.uiuxDesignDesc": "Красивые, интуитивные интерфейсы, которые нравятся пользователям. Дизайн, сочетающий эстетику с функциональностью.",
    "services.uiuxFeature1": "Дизайн интерфейсов",
    "services.uiuxFeature2": "UX исследования",
    "services.uiuxFeature3": "Прототипирование и вайрфреймы",
    "services.uiuxFeature4": "Дизайн-системы",
    "services.ourProcess": "Наш процесс",
    "services.processSubtitle": "// Как мы воплощаем вашу идею",
    "services.step1": "Исследование",
    "services.step1Desc": "Изучаем ваши цели, аудиторию и требования.",
    "services.step2": "Планирование",
    "services.step2Desc": "Детальная дорожная карта, архитектурные решения и оценка сроков.",
    "services.step3": "Разработка",
    "services.step3Desc": "Agile-разработка с регулярными обновлениями и циклами обратной связи.",
    "services.step4": "Запуск",
    "services.step4Desc": "Тщательное тестирование, развёртывание и поддержка после запуска.",
    "services.techStack": "Технологии",
    "services.techStackSubtitle": "// С какими технологиями мы работаем",
    "services.readyToStart": "Готовы начать проект?",
    "services.ctaDesc": "Давайте обсудим ваши идеи и создадим что-то потрясающее вместе.",
    "services.getInTouch": "Связаться",

    // Works Page
    "works.terminalPath": "~/портфолио/работы",
    "works.title": "Наши работы",
    "works.subtitle": "Исследуйте наше портфолио:",
    "works.websites": "сайты",
    "works.games": "игры",
    "works.mobileApps": "мобильные приложения",
    "works.designs": "дизайны",
    "works.weCrafted": ", которые мы создали.",
    "works.totalProjects": "Всего проектов",
    "works.completed": "Завершено",
    "works.inProgress": "В работе",
    "works.comingSoon": "Скоро",
    "works.allProjects": "Все проекты",
    "works.web": "Веб",
    "works.gamesFilter": "Игры",
    "works.mobile": "Мобильные",
    "works.design": "Дизайн",
    "works.viewLive": "Открыть",
    "works.detailsSoon": "[Скоро]",
    "works.haveProject": "Есть",
    "works.projectInMind": "проект",
    "works.inMind": "на уме?",
    "works.ctaDesc": "Мы всегда рады новым вызовам. Давайте создадим что-то потрясающее вместе.",
    "works.startProject": "Начать проект",

    // Demos Page
    "demos.terminalPath": "~/песочница/демо",
    "demos.title": "Интерактивные демо",
    "demos.subtitle": "Попробуйте наши",
    "demos.games": "игры",
    "demos.webExperiments": "веб-эксперименты",
    "demos.prototypes": "интерактивные прототипы",
    "demos.inBrowser": "прямо в браузере.",
    "demos.all": "Все",
    "demos.gamesFilter": "Игры",
    "demos.webFilter": "Веб",
    "demos.mobileFilter": "Мобильные",
    "demos.experiments": "Эксперименты",
    "demos.playDemo": "Играть",
    "demos.download": "Скачать",
    "demos.featured": "Избранное",
    "demos.fullscreen": "На весь экран",
    "demos.share": "Поделиться",
    "demos.instantPlay": "Мгновенный запуск",
    "demos.instantPlayDesc": "Без загрузок. Все демо работают прямо в браузере с WebGL и современными веб-API.",
    "demos.crossPlatform": "Кроссплатформенность",
    "demos.crossPlatformDesc": "Работает на ПК, планшете и телефоне. Управление адаптируется под ваше устройство.",
    "demos.openSource": "Открытый код",
    "demos.openSourceDesc": "Многие демо с открытым кодом. Смотрите наш GitHub для исходников и обучающих материалов.",

    // Blog Page
    "blog.terminalPath": "~/контент/блог",
    "blog.title": "Блог",
    "blog.subtitle": "от команды BI3.",
    "blog.tutorials": "Туториалы",
    "blog.techInsights": "tech-инсайты",
    "blog.devLogs": "девлоги",
    "blog.news": "новости",
    "blog.searchPosts": "Поиск статей...",
    "blog.allPosts": "Все статьи",
    "blog.tech": "Технологии",
    "blog.tutorial": "Туториал",
    "blog.newsFilter": "Новости",
    "blog.devLog": "Девлог",
    "blog.featuredPosts": "Избранные статьи",
    "blog.latestPosts": "Последние статьи",
    "blog.noPosts": "Статьи не найдены.",
    "blog.clearFilters": "Сбросить фильтры",
    "blog.stayUpdated": "Будьте",
    "blog.updated": "в курсе",
    "blog.newsletterDesc": "Подпишитесь на рассылку для получения последних туториалов, девлогов и tech-инсайтов.",
    "blog.emailPlaceholder": "ваш@email.com",
    "blog.subscribe": "Подписаться",
    "blog.noSpam": "Без спама. Отписка в любое время.",
    "blog.minRead": "мин чтения",

    // Contact Page
    "contact.terminalPath": "~/связь/контакты",
    "contact.title": "Связаться с нами",
    "contact.subtitle": "Есть проект? Хотите сотрудничать? Или просто поздороваться?",
    "contact.loveToHear": "Будем рады услышать вас.",
    "contact.quickContact": "Быстрая связь",
    "contact.emailUs": "Email",
    "contact.telegram": "Телеграм",
    "contact.discord": "Дискорд",
    "contact.community": "Сообщество BI3",
    "contact.location": "Локация",
    "contact.basedIn": "Расположены в",
    "contact.availableRemote": "Доступны для удалённой работы по всему миру",
    "contact.followUs": "Мы в соцсетях",
    "contact.startProject": "Начать проект",
    "contact.formDesc": "Заполните форму, и мы ответим в течение 24 часов.",
    "contact.name": "Имя",
    "contact.email": "Email",
    "contact.subject": "Тема",
    "contact.projectType": "Тип проекта",
    "contact.selectType": "Выберите тип...",
    "contact.website": "Веб-сайт",
    "contact.webApp": "Веб-приложение",
    "contact.mobileApp": "Мобильное приложение",
    "contact.game": "Игра",
    "contact.design": "UI/UX Дизайн",
    "contact.other": "Другое",
    "contact.budget": "Бюджет",
    "contact.selectBudget": "Выберите бюджет...",
    "contact.letsDiscuss": "Обсудим",
    "contact.message": "Сообщение",
    "contact.messagePlaceholder": "Расскажите о вашем проекте...",
    "contact.sendMessage": "Отправить",
    "contact.sending": "Отправка...",
    "contact.messageSent": "Отправлено!",
    "contact.thankYou": "Спасибо за обращение. Мы скоро свяжемся с вами.",
    "contact.sendAnother": "Отправить ещё",
    "contact.faq": "Частые вопросы",
    "contact.faq1Q": "Какое у вас время ответа?",
    "contact.faq1A": "Обычно мы отвечаем в течение 24 часов в рабочие дни. Для срочных вопросов пишите в Telegram.",
    "contact.faq2Q": "Работаете ли вы с международными клиентами?",
    "contact.faq2A": "Конечно! Мы работаем с клиентами по всему миру. Наша команда имеет опыт удалённого сотрудничества в разных часовых поясах.",
    "contact.faq3Q": "На каких технологиях вы специализируетесь?",
    "contact.faq3A": "Мы специализируемся на React/Next.js, Unity/Godot для игр, React Native/Flutter для мобильных приложений и современных инструментах дизайна, таких как Figma.",
    "contact.faq4Q": "Как вы оцениваете проекты?",
    "contact.faq4A": "Мы предлагаем как фиксированную цену, так и почасовую оплату в зависимости от объёма проекта. Мы предоставим детальную оценку после изучения ваших требований.",

    // Footer
    "footer.description": "Молодая студия разработки, создающая исключительные сайты, игры и мобильные приложения из Ташкента, Узбекистан.",
    "footer.navigation": "Навигация",
    "footer.services": "Услуги",
    "footer.connect": "Связь",
    "footer.rights": "Все права защищены.",
    "footer.partOf": "Часть",

    // Games Service Page
    "games.title": "Разработка",
    "games.title2": "Игр",
    "games.description": "От концепт-арта до финального релиза — мы воплощаем вашу игровую идею в жизнь.",
    "games.startGame": "Начать игру",
    "games.playDemos": "Играть в демо",
    "games.interactiveDemo": "// Интерактивная демо - Кликните для навигации",
    "games.whatWeCreate": "Что мы создаём",
    "games.whatWeCreateDesc": "// Полный цикл разработки игр",
    "games.pcGames": "ПК Игры",
    "games.pcGamesDesc": "Высокопроизводительные игры для Windows, Mac и Linux с потрясающей графикой.",
    "games.mobileGames": "Мобильные игры",
    "games.mobileGamesDesc": "Увлекательные игры для iOS и Android, оптимизированные для сенсорного управления.",
    "games.browserGames": "Браузерные игры",
    "games.browserGamesDesc": "WebGL и HTML5 игры, работающие прямо в браузере без загрузки.",
    "games.3dDev": "3D Разработка",
    "games.3dDevDesc": "Иммерсивные 3D миры с реалистичной физикой, освещением и окружением.",
    "games.2dArt": "2D Арт и Анимация",
    "games.2dArtDesc": "Красивая 2D графика, спрайтовые анимации и визуальные эффекты.",
    "games.soundMusic": "Звук и Музыка",
    "games.soundMusicDesc": "Оригинальные саундтреки, звуковые эффекты и иммерсивный аудио-дизайн.",
    "games.gameGenres": "Жанры игр",
    "games.gameGenresDesc": "// Разрабатываем во всех жанрах",
    "games.techStack": "Технологии",
    "games.techStackDesc": "// Индустриальные инструменты и движки",
    "games.devProcess": "Процесс разработки",
    "games.devProcessDesc": "// От идеи до запуска",
    "games.concept": "Концепт",
    "games.conceptDesc": "Документ игрового дизайна, сюжет, планирование механик",
    "games.prototype": "Прототип",
    "games.prototypeDesc": "Основной игровой цикл, тестирование базовых механик",
    "games.production": "Продакшн",
    "games.productionDesc": "Полная разработка, арт, звук, полировка",
    "games.launch": "Запуск",
    "games.launchDesc": "Тестирование, оптимизация, релиз, поддержка",
    "games.readyTo": "Готовы",
    "games.levelUp": "прокачаться?",
    "games.ctaDesc": "Давайте создадим незабываемый игровой опыт вместе.",
    "games.startProject": "Начать проект",
    "games.viewGames": "Наши игры",
    "games.action": "Экшен",
    "games.adventure": "Приключения",
    "games.rpg": "РПГ",
    "games.puzzle": "Головоломки",
    "games.platformer": "Платформер",
    "games.shooter": "Шутер",
    "games.strategy": "Стратегия",
    "games.simulation": "Симулятор",
    "games.racing": "Гонки",
    "games.horror": "Хоррор",
    // Game Menu Demo
    "games.menu.mainMenu": "ГЛАВНОЕ МЕНЮ",
    "games.menu.selectMode": "ВЫБОР РЕЖИМА",
    "games.menu.settings": "НАСТРОЙКИ",
    "games.menu.language": "ЯЗЫК",
    "games.menu.play": "ИГРАТЬ",
    "games.menu.quit": "ВЫХОД",
    "games.menu.singlePlayer": "ОДИНОЧНАЯ ИГРА",
    "games.menu.playWithFriends": "ИГРАТЬ С ДРУЗЬЯМИ",
    "games.menu.back": "НАЗАД",
    "games.menu.graphics": "ГРАФИКА",
    "games.menu.audio": "ЗВУК",
    "games.menu.controls": "УПРАВЛЕНИЕ",
    "games.menu.clickToSelect": "НАЖМИТЕ ДЛЯ ВЫБОРА",

    // Web Development Service Page
    "web.title": "Веб",
    "web.title2": "Разработка",
    "web.description": "От концепции до развёртывания — создаём современные, масштабируемые веб-решения.",
    "web.startProject": "Начать проект",
    "web.viewWorks": "Наши работы",
    "web.interactiveDemo": "// Интерактивная демо - Живой просмотр",
    "web.whatWeCreate": "Что мы создаём",
    "web.whatWeCreateDesc": "// Полный цикл веб-разработки",
    "web.landingPages": "Лендинги",
    "web.landingPagesDesc": "Конверсионные лендинги с потрясающим дизайном и оптимальной производительностью.",
    "web.webApps": "Веб-приложения",
    "web.webAppsDesc": "Сложные веб-приложения с богатым функционалом и бесшовным UX.",
    "web.ecommerce": "Интернет-магазины",
    "web.ecommerceDesc": "Онлайн-магазины с безопасными платежами, управлением запасами и аналитикой.",
    "web.dashboards": "Дашборды",
    "web.dashboardsDesc": "Панели визуализации данных с обновлениями в реальном времени и интерактивными графиками.",
    "web.apis": "Разработка API",
    "web.apisDesc": "RESTful и GraphQL API с аутентификацией, лимитами и документацией.",
    "web.cms": "CMS Решения",
    "web.cmsDesc": "Кастомные системы управления контентом под ваши нужды.",
    "web.techStack": "Технологии",
    "web.techStackDesc": "// Современные технологии, с которыми мы работаем",
    "web.frontend": "Фронтенд",
    "web.backend": "Бэкенд",
    "web.database": "Базы данных",
    "web.devops": "DevOps",
    "web.devProcess": "Процесс разработки",
    "web.devProcessDesc": "// От идеи до запуска",
    "web.discovery": "Исследование",
    "web.discoveryDesc": "Сбор требований, исследование пользователей, объём проекта",
    "web.design": "Дизайн",
    "web.designDesc": "Вайрфреймы, UI/UX дизайн, прототипирование",
    "web.development": "Разработка",
    "web.developmentDesc": "Фронтенд, бэкенд, база данных, тестирование",
    "web.deployment": "Развёртывание",
    "web.deploymentDesc": "Запуск, мониторинг, поддержка",
    "web.readyTo": "Готовы",
    "web.goOnline": "выйти в сеть?",
    "web.ctaDesc": "Давайте создадим ваше цифровое присутствие вместе.",
    "web.startProjectBtn": "Начать проект",
    "web.viewPortfolio": "Портфолио",
    "web.features": "Ключевые особенности",
    "web.featuresDesc": "// Что выделяет наши сайты",
    "web.responsive": "Адаптивный дизайн",
    "web.responsiveDesc": "Идеально на всех устройствах — ПК, планшет и мобильный.",
    "web.seo": "SEO оптимизация",
    "web.seoDesc": "Создано для поисковиков с лучшими практиками и быстрой загрузкой.",
    "web.secure": "Безопасно и надёжно",
    "web.secureDesc": "Стандарты безопасности с SSL, аутентификацией и защитой данных.",
    "web.scalable": "Масштабируемая архитектура",
    "web.scalableDesc": "Создано для роста вместе с вашим бизнесом.",
    "web.fast": "Молниеносная скорость",
    "web.fastDesc": "Оптимизированная производительность с кэшированием и CDN.",
    "web.accessible": "Доступность",
    "web.accessibleDesc": "Соответствие WCAG для пользователей с любыми возможностями.",

    // Mobile Development Service Page
    "mobile.title": "Мобильная",
    "mobile.title2": "Разработка",
    "mobile.description": "Нативные и кроссплатформенные приложения, которые любят пользователи.",
    "mobile.startProject": "Создать приложение",
    "mobile.viewApps": "Наши приложения",
    "mobile.interactiveDemo": "// Интерактивная демо - Свайпайте для навигации",
    "mobile.whatWeCreate": "Что мы создаём",
    "mobile.whatWeCreateDesc": "// Полный цикл мобильной разработки",
    "mobile.iosApps": "iOS приложения",
    "mobile.iosAppsDesc": "Нативные Swift приложения для iPhone и iPad по гайдлайнам Apple.",
    "mobile.androidApps": "Android приложения",
    "mobile.androidAppsDesc": "Нативные Kotlin приложения для всей экосистемы Android.",
    "mobile.crossPlatform": "Кроссплатформа",
    "mobile.crossPlatformDesc": "React Native и Flutter приложения для обеих платформ из единой кодовой базы.",
    "mobile.appDesign": "UI/UX приложений",
    "mobile.appDesignDesc": "Красивые, интуитивные интерфейсы по гайдлайнам платформ.",
    "mobile.backend": "Бэкенд и API",
    "mobile.backendDesc": "Масштабируемая серверная инфраструктура и синхронизация в реальном времени.",
    "mobile.maintenance": "Поддержка",
    "mobile.maintenanceDesc": "Постоянные обновления, исправления багов и оптимизация.",
    "mobile.techStack": "Технологии",
    "mobile.techStackDesc": "// Ведущие мобильные технологии",
    "mobile.ios": "iOS",
    "mobile.android": "Android",
    "mobile.crossPlatformTech": "Кроссплатформа",
    "mobile.backendTech": "Бэкенд",
    "mobile.devProcess": "Процесс разработки",
    "mobile.devProcessDesc": "// От концепции до App Store",
    "mobile.ideation": "Идея",
    "mobile.ideationDesc": "Исследование рынка, планирование функций, техническая оценка",
    "mobile.design": "Дизайн",
    "mobile.designDesc": "Вайрфреймы, прототипы, UI/UX дизайн",
    "mobile.development": "Разработка",
    "mobile.developmentDesc": "Нативная/кроссплатформенная разработка, интеграция API",
    "mobile.launch": "Запуск",
    "mobile.launchDesc": "Тестирование, публикация в App Store, поддержка",
    "mobile.readyTo": "Готовы",
    "mobile.goMobile": "стать мобильными?",
    "mobile.ctaDesc": "Давайте воплотим вашу идею приложения в жизнь.",
    "mobile.startProjectBtn": "Начать проект",
    "mobile.viewPortfolio": "Портфолио",
    "mobile.features": "Возможности приложений",
    "mobile.featuresDesc": "// Что выделяет наши приложения",
    "mobile.offline": "Офлайн режим",
    "mobile.offlineDesc": "Работает без подключения к интернету.",
    "mobile.push": "Push-уведомления",
    "mobile.pushDesc": "Вовлекайте пользователей актуальными уведомлениями.",
    "mobile.analytics": "Аналитика",
    "mobile.analyticsDesc": "Отслеживание поведения пользователей и производительности.",
    "mobile.security": "Безопасность",
    "mobile.securityDesc": "Шифрование данных, безопасная аутентификация, приватность.",
    "mobile.performance": "Производительность",
    "mobile.performanceDesc": "Плавные 60fps анимации, быстрая загрузка.",
    "mobile.updates": "OTA обновления",
    "mobile.updatesDesc": "Обновления без ревью App Store.",

    // UI/UX Design Service Page
    "design.title": "UI/UX",
    "design.title2": "Дизайн",
    "design.description": "Красивые, интуитивные интерфейсы, которые любят пользователи.",
    "design.startProject": "Начать дизайн",
    "design.viewWorks": "Наши дизайны",
    "design.interactiveDemo": "// Интерактивная демо - Нажмите для изучения",
    "design.whatWeCreate": "Что мы создаём",
    "design.whatWeCreateDesc": "// Полный цикл дизайн-услуг",
    "design.uiDesign": "UI Дизайн",
    "design.uiDesignDesc": "Пиксель-перфектные интерфейсы с современной эстетикой и вниманием к деталям.",
    "design.uxResearch": "UX Исследования",
    "design.uxResearchDesc": "Интервью, опросы и юзабилити-тесты для понимания вашей аудитории.",
    "design.wireframes": "Вайрфреймы",
    "design.wireframesDesc": "Низко- и высокодетализированные вайрфреймы для визуализации пути пользователя.",
    "design.prototyping": "Прототипирование",
    "design.prototypingDesc": "Интерактивные прототипы для тестирования и презентаций.",
    "design.designSystems": "Дизайн-системы",
    "design.designSystemsDesc": "Масштабируемые библиотеки компонентов и гайдлайны для консистентности.",
    "design.branding": "Брендинг",
    "design.brandingDesc": "Дизайн логотипа, цветовые палитры, типографика и айдентика.",
    "design.tools": "Инструменты",
    "design.toolsDesc": "// Профессиональное ПО, которое мы используем",
    "design.designTools": "Дизайн",
    "design.prototypeTools": "Прототипирование",
    "design.collaborationTools": "Совместная работа",
    "design.devHandoff": "Передача разработчикам",
    "design.devProcess": "Процесс дизайна",
    "design.devProcessDesc": "// От исследования до передачи",
    "design.research": "Исследование",
    "design.researchDesc": "UX исследования, анализ конкурентов, сбор требований",
    "design.ideate": "Идеация",
    "design.ideateDesc": "Скетчи, вайрфреймы, информационная архитектура",
    "design.designStep": "Дизайн",
    "design.designStepDesc": "Визуальный дизайн, прототипирование, юзер-тестинг",
    "design.handoff": "Передача",
    "design.handoffDesc": "Спецификации, экспорт ассетов, поддержка внедрения",
    "design.readyTo": "Готовы",
    "design.standOut": "выделиться?",
    "design.ctaDesc": "Давайте создадим дизайн, который производит впечатление.",
    "design.startProjectBtn": "Начать проект",
    "design.viewPortfolio": "Портфолио",
    "design.features": "Принципы дизайна",
    "design.featuresDesc": "// Что направляет наши решения",
    "design.userCentered": "Ориентация на пользователя",
    "design.userCenteredDesc": "Каждое решение подкреплено потребностями и исследованиями.",
    "design.accessible": "Доступность",
    "design.accessibleDesc": "Инклюзивный дизайн для пользователей с любыми возможностями.",
    "design.consistent": "Консистентность",
    "design.consistentDesc": "Единый визуальный язык на всех точках контакта.",
    "design.responsive": "Адаптивность",
    "design.responsiveDesc": "Безупречный опыт на любом размере экрана.",
    "design.delightful": "Восхищение",
    "design.delightfulDesc": "Микро-взаимодействия и анимации, которые вовлекают.",
    "design.scalable": "Масштабируемость",
    "design.scalableDesc": "Дизайн-системы, растущие вместе с продуктом.",
  },
  uz: {
    // Navigation
    "nav.home": "Bosh sahifa",
    "nav.about": "Biz haqimizda",
    "nav.services": "Xizmatlar",
    "nav.works": "Ishlar",
    "nav.demos": "Demo",
    "nav.blog": "Blog",
    "nav.contact": "Aloqa",

    // Home Page
    "home.tagline1": "Yosh",
    "home.tagline2": "dasturchilar.",
    "home.tagline3": "Katta",
    "home.tagline4": "g'oyalar.",
    "home.description": "Biz",
    "home.description2": "5 ta ishtiyoqli dasturchi",
    "home.description3": "jamoasimiz",
    "home.description4": "Toshkent, O'zbekiston",
    "home.description5": "dan, ajoyib veb-saytlar, o'yinlar va mobil ilovalar yaratamiz.",
    "home.description6": "Yosh 14-21",
    "home.description7": ", kod bilan birlashgan.",
    "home.viewWork": "Ishlarimiz",
    "home.getInTouch": "Bog'lanish",
    "home.scroll": "Pastga",
    "home.projects": "Loyihalar",
    "home.hackers": "Hakerlar",
    "home.years": "Yillar",
    "home.technologies": "Texnologiyalar",
    "home.whatWeBuild": "Biz nima yaratamiz",
    "home.whatWeBuildDesc": "// Turli platformalar uchun sifatli raqamli mahsulotlar",
    "home.webDev": "Veb-dasturlash",
    "home.webDevDesc": "Zamonaviy, moslashuvchan saytlar va veb-ilovalar.",
    "home.gameDev": "O'yin yaratish",
    "home.gameDevDesc": "Turli platformalar uchun qiziqarli o'yin tajribalari.",
    "home.mobileApps": "Mobil ilovalar",
    "home.mobileAppsDesc": "iOS va Android uchun mahalliy ilovalar.",
    "home.uiuxDesign": "UI/UX Dizayn",
    "home.uiuxDesignDesc": "Futuristik, intuitiv interfeyslar.",
    "home.networkConnections": "TARMOQ ALOQALARI",
    "home.readyToBuild": "Ajoyib narsa",
    "home.toBuildSomething": "yaratishga",
    "home.amazing": "tayyormisiz",
    "home.ctaDescription": "Kelajakni birga yarataylik. Bugun biz bilan bog'laning.",
    "home.startProject": "Loyihani boshlash",

    // About Page
    "about.terminalPath": "~/haqida/bi3",
    "about.title": "Biz haqimizda",
    "about.subtitle": "Toshkentlik besh yosh dasturchining hikoyasi, kelajakni qator-qator qurayotgan.",
    "about.ourStory": "Bizning hikoyamiz",
    "about.storyP1": "BI3 texnologiya va yaratishga bo'lgan umumiy ishtiyoqdan tug'ildi. Biz Toshkent, O'zbekistondan 14-21 yoshdagi besh dasturchidan iborat jamoamiz. Kod bilan tajriba o'tkazayotgan do'stlar guruhi sifatida boshlangan narsa to'laqonli dasturlash studiyasiga aylandi.",
    "about.storyP2": "Biz veb-dasturlash, o'yin yaratish va mobil ilovalar bo'yicha ixtisoslashganmiz. Yoshligimiz bizning kuchimiz - biz har bir loyihaga yangi qarashlar, cheksiz energiya va to'ymas qiziqishni olib kelamiz.",
    "about.storyP3": "Natex Labs ekotizimining bir qismi va FirstIt hamkorlari sifatida, biz texnologiyada mumkin bo'lgan chegaralarni kengaytirishga intilamiz.",
    "about.leadingBi3": "BI3 Jamoasi",
    "about.ourValues": "Bizning qadriyatlarimiz",
    "about.valuesSubtitle": "// Ishimizni yo'naltiruvchi tamoyillar",
    "about.innovation": "Innovatsiya",
    "about.innovationDesc": "Biz yangi texnologiyalar va yondashuvlarni qabul qilamiz, doimo oldinda turamiz.",
    "about.quality": "Sifat",
    "about.qualityDesc": "Har bir qator kod ehtiyotkorlik bilan yozilgan. Mukammal bo'lmaguncha chiqarmaymiz.",
    "about.collaboration": "Hamkorlik",
    "about.collaborationDesc": "Ishtiyoqli odamlar birga ishlaganda ajoyib narsalar sodir bo'ladi.",
    "about.growth": "O'sish",
    "about.growthDesc": "Biz doimo o'rganamiz, doimo takomillashamiz, doimo rivojlanamiz.",
    "about.ourPartners": "Bizning hamkorlarimiz",
    "about.partnersSubtitle": "// Tech ekotizimidagi ishonchli aloqalar",
    "about.location": "Joylashuv",
    "about.locationSubtitle": "// Innovatsiya an'ana bilan uchrashgan joy",
    "about.basedIn": "Joylashgan",
    "about.tashkent": "Toshkent, O'zbekiston",
    "about.availableWorldwide": "Butun dunyo bo'ylab masofaviy ishlash uchun tayyor",

    // Team Members
    "team.member1.name": "Ibrohim A.",
    "team.member1.role": "CEO va Asoschisi",
    "team.member1.bio": "BI3ning raqamli rivojlanishni inqilob qilish missiyasini boshqaruvchi rahbar. Innovatsion yechimlar yaratishga ishtiyoqli.",
    "team.member2.name": "Ibrohim R.",
    "team.member2.role": "Loyiha Menejeri",
    "team.member2.bio": "Loyihalarni kontseptsiyadan yakunigacha boshqarish. Agile metodologiyalari va jamoa muvofiqlashtirish bo'yicha ekspert.",
    "team.member3.name": "Ibrohim U.",
    "team.member3.role": "Front End Dasturchi",
    "team.member3.bio": "Zamonaviy veb-texnologiyalar bilan ajoyib foydalanuvchi interfeyslarini yaratish. Ishlash va foydalanuvchi tajribasiga e'tibor.",
    "team.member4.name": "Begzod",
    "team.member4.role": "Backend Dasturchi",
    "team.member4.bio": "Ishonchli server tomonidagi yechimlar va API'larni qurish. Ma'lumotlar bazasi arxitekturasi va tizim dizayni bo'yicha ekspert.",
    "team.member5.name": "Ibrohim I.",
    "team.member5.role": "Web3 va Blockchain Dasturchi",
    "team.member5.bio": "Markazlashmagan yechimlar va smart-kontraktlar bo'yicha kashshof. BI3 loyihalariga blockchain innovatsiyalarini olib kelish.",
    "team.skill.leadership": "Rahbarlik",
    "team.skill.strategy": "Strategiya",
    "team.skill.business": "Biznes rivojlantirish",
    "team.skill.agile": "Agile",
    "team.skill.scrum": "Scrum",
    "team.skill.management": "Jamoa boshqaruvi",
    "team.skill.planning": "Loyiha rejalashtirish",
    "team.skill.smartContracts": "Smart-kontraktlar",

    // Services Page
    "services.terminalPath": "~/xizmatlar",
    "services.title": "Bizning xizmatlarimiz",
    "services.subtitle": "Kontseptsiyadan ishga tushirishgacha keng qamrovli raqamli yechimlar. G'oyalaringizni zamonaviy texnologiyalar bilan hayotga tatbiq etamiz.",
    "services.webDev": "Veb-dasturlash",
    "services.webDevDesc": "Zamonaviy, moslashuvchan va samarali veb-saytlar va ilovalar. Landing sahifalardan murakkab platformalargacha.",
    "services.webDevFeature1": "Maxsus saytlar va landing sahifalar",
    "services.webDevFeature2": "Veb-ilovalar va boshqaruv panellari",
    "services.webDevFeature3": "E-tijorat yechimlari",
    "services.webDevFeature4": "API ishlab chiqish va integratsiya",
    "services.gameDev": "O'yin yaratish",
    "services.gameDevDesc": "Turli platformalar uchun qiziqarli o'yinlar. Oddiy mobil o'yinlardan immersiv 3D tajribalargacha.",
    "services.gameDevFeature1": "2D va 3D o'yinlar",
    "services.gameDevFeature2": "Mobil o'yinlar (iOS/Android)",
    "services.gameDevFeature3": "Kompyuter va brauzer o'yinlari",
    "services.gameDevFeature4": "O'yin dizayni va mexanikasi",
    "services.mobileDev": "Mobil dasturlash",
    "services.mobileDevDesc": "Ajoyib foydalanuvchi tajribasini taqdim etuvchi mahalliy va kross-platforma mobil ilovalari.",
    "services.mobileDevFeature1": "iOS ilovalarini ishlab chiqish",
    "services.mobileDevFeature2": "Android ilovalarini ishlab chiqish",
    "services.mobileDevFeature3": "Kross-platforma yechimlari",
    "services.mobileDevFeature4": "App Store optimallashtirish",
    "services.uiuxDesign": "UI/UX Dizayn",
    "services.uiuxDesignDesc": "Foydalanuvchilar yoqtiradigan chiroyli, intuitiv interfeyslar. Estetika va funksionallikni birlashtirgan dizayn.",
    "services.uiuxFeature1": "Interfeys dizayni",
    "services.uiuxFeature2": "UX tadqiqotlari",
    "services.uiuxFeature3": "Prototiplash va wireframe",
    "services.uiuxFeature4": "Dizayn tizimlari",
    "services.ourProcess": "Bizning jarayonimiz",
    "services.processSubtitle": "// G'oyangizni qanday hayotga tatbiq etamiz",
    "services.step1": "Kashfiyot",
    "services.step1Desc": "Maqsadlaringiz, auditoriyangiz va talablaringizni o'rganamiz.",
    "services.step2": "Rejalashtirish",
    "services.step2Desc": "Batafsil yo'l xaritasi, arxitektura qarorlari va muddat baholash.",
    "services.step3": "Ishlab chiqish",
    "services.step3Desc": "Muntazam yangilanishlar va qayta aloqa tsikllari bilan Agile ishlab chiqish.",
    "services.step4": "Ishga tushirish",
    "services.step4Desc": "Puxta sinovlar, joylashtirish va ishga tushirishdan keyingi qo'llab-quvvatlash.",
    "services.techStack": "Texnologiyalar",
    "services.techStackSubtitle": "// Qaysi texnologiyalar bilan ishlaymiz",
    "services.readyToStart": "Loyihangizni boshlashga tayyormisiz?",
    "services.ctaDesc": "G'oyalaringizni muhokama qilaylik va birga ajoyib narsa yarataylik.",
    "services.getInTouch": "Bog'lanish",

    // Works Page
    "works.terminalPath": "~/portfolio/ishlar",
    "works.title": "Bizning ishlarimiz",
    "works.subtitle": "Portfoliomizni ko'ring:",
    "works.websites": "veb-saytlar",
    "works.games": "o'yinlar",
    "works.mobileApps": "mobil ilovalar",
    "works.designs": "dizaynlar",
    "works.weCrafted": " biz yaratgan.",
    "works.totalProjects": "Jami loyihalar",
    "works.completed": "Tugallangan",
    "works.inProgress": "Jarayonda",
    "works.comingSoon": "Tez kunda",
    "works.allProjects": "Barcha loyihalar",
    "works.web": "Veb",
    "works.gamesFilter": "O'yinlar",
    "works.mobile": "Mobil",
    "works.design": "Dizayn",
    "works.viewLive": "Ochish",
    "works.detailsSoon": "[Tez kunda]",
    "works.haveProject": "Loyiha",
    "works.projectInMind": "bormi",
    "works.inMind": "xayolingizda?",
    "works.ctaDesc": "Biz doimo yangi vazifalarni bajarishga tayyormiz. Birga ajoyib narsa yarataylik.",
    "works.startProject": "Loyihani boshlash",

    // Demos Page
    "demos.terminalPath": "~/o'yin-maydoni/demo",
    "demos.title": "Interaktiv demolar",
    "demos.subtitle": "Bizning",
    "demos.games": "o'yinlarimiz",
    "demos.webExperiments": "veb-tajribalarimiz",
    "demos.prototypes": "interaktiv prototiplarni",
    "demos.inBrowser": "brauzeringizda sinab ko'ring.",
    "demos.all": "Hammasi",
    "demos.gamesFilter": "O'yinlar",
    "demos.webFilter": "Veb",
    "demos.mobileFilter": "Mobil",
    "demos.experiments": "Tajribalar",
    "demos.playDemo": "O'ynash",
    "demos.download": "Yuklab olish",
    "demos.featured": "Tanlangan",
    "demos.fullscreen": "To'liq ekran",
    "demos.share": "Ulashish",
    "demos.instantPlay": "Tezkor ishga tushirish",
    "demos.instantPlayDesc": "Yuklab olish shart emas. Barcha demolar WebGL va zamonaviy veb API bilan to'g'ridan-to'g'ri brauzeringizda ishlaydi.",
    "demos.crossPlatform": "Kross-platforma",
    "demos.crossPlatformDesc": "Kompyuter, planshet va telefonda ishlaydi. Boshqaruvlar qurilmangizga moslashadi.",
    "demos.openSource": "Ochiq manba",
    "demos.openSourceDesc": "Ko'p demolar ochiq kodli. Manba kodlari va o'quv materiallari uchun GitHub sahifamizni ko'ring.",

    // Blog Page
    "blog.terminalPath": "~/kontent/blog",
    "blog.title": "Blog",
    "blog.subtitle": "BI3 jamoasidan.",
    "blog.tutorials": "Darsliklar",
    "blog.techInsights": "tech-tushunchalar",
    "blog.devLogs": "devloglar",
    "blog.news": "yangiliklar",
    "blog.searchPosts": "Maqolalarni qidirish...",
    "blog.allPosts": "Barcha maqolalar",
    "blog.tech": "Texnologiya",
    "blog.tutorial": "Darslik",
    "blog.newsFilter": "Yangiliklar",
    "blog.devLog": "Devlog",
    "blog.featuredPosts": "Tanlangan maqolalar",
    "blog.latestPosts": "So'nggi maqolalar",
    "blog.noPosts": "Maqolalar topilmadi.",
    "blog.clearFilters": "Filtrlarni tozalash",
    "blog.stayUpdated": "Xabardor",
    "blog.updated": "bo'ling",
    "blog.newsletterDesc": "So'nggi darsliklar, devloglar va tech-tushunchalar uchun obuna bo'ling.",
    "blog.emailPlaceholder": "sizning@email.com",
    "blog.subscribe": "Obuna bo'lish",
    "blog.noSpam": "Spam yo'q. Istalgan vaqtda obunani bekor qilish.",
    "blog.minRead": "daqiqa o'qish",

    // Contact Page
    "contact.terminalPath": "~/aloqa/kontakt",
    "contact.title": "Bog'lanish",
    "contact.subtitle": "Loyiha bormi? Hamkorlik qilmoqchimisiz? Yoki shunchaki salom aytmoqchimisiz?",
    "contact.loveToHear": "Sizdan xabar olishdan xursand bo'lamiz.",
    "contact.quickContact": "Tezkor aloqa",
    "contact.emailUs": "Email",
    "contact.telegram": "Telegram",
    "contact.discord": "Discord",
    "contact.community": "BI3 Hamjamiyati",
    "contact.location": "Joylashuv",
    "contact.basedIn": "Joylashgan",
    "contact.availableRemote": "Butun dunyo bo'ylab masofaviy ishlash uchun tayyor",
    "contact.followUs": "Bizni kuzating",
    "contact.startProject": "Loyihani boshlash",
    "contact.formDesc": "Formani to'ldiring va biz 24 soat ichida javob beramiz.",
    "contact.name": "Ism",
    "contact.email": "Email",
    "contact.subject": "Mavzu",
    "contact.projectType": "Loyiha turi",
    "contact.selectType": "Turni tanlang...",
    "contact.website": "Veb-sayt",
    "contact.webApp": "Veb-ilova",
    "contact.mobileApp": "Mobil ilova",
    "contact.game": "O'yin",
    "contact.design": "UI/UX Dizayn",
    "contact.other": "Boshqa",
    "contact.budget": "Byudjet",
    "contact.selectBudget": "Byudjetni tanlang...",
    "contact.letsDiscuss": "Muhokama qilamiz",
    "contact.message": "Xabar",
    "contact.messagePlaceholder": "Loyihangiz haqida gapirib bering...",
    "contact.sendMessage": "Yuborish",
    "contact.sending": "Yuborilmoqda...",
    "contact.messageSent": "Yuborildi!",
    "contact.thankYou": "Murojaat uchun rahmat. Tez orada aloqaga chiqamiz.",
    "contact.sendAnother": "Yana yuborish",
    "contact.faq": "Ko'p so'raladigan",
    "contact.faq1Q": "Javob berish vaqtingiz qancha?",
    "contact.faq1A": "Odatda ish kunlarida 24 soat ichida javob beramiz. Shoshilinch so'rovlar uchun Telegramga yozing.",
    "contact.faq2Q": "Xalqaro mijozlar bilan ishlaysizmi?",
    "contact.faq2A": "Albatta! Biz butun dunyo bo'ylab mijozlar bilan ishlaymiz. Jamoamiz turli vaqt zonalarida masofaviy hamkorlik tajribasiga ega.",
    "contact.faq3Q": "Qaysi texnologiyalarda ixtisoslashgansiz?",
    "contact.faq3A": "Biz React/Next.js, o'yinlar uchun Unity/Godot, mobil ilovalar uchun React Native/Flutter va Figma kabi zamonaviy dizayn vositalarida ixtisoslashganmiz.",
    "contact.faq4Q": "Loyihalarni qanday baholaysiz?",
    "contact.faq4A": "Loyiha hajmiga qarab belgilangan narx va soatlik to'lov variantlarini taklif qilamiz. Talablaringizni o'rganganingizdan so'ng batafsil narx taklifi beramiz.",

    // Footer
    "footer.description": "Toshkent, O'zbekistondan ajoyib veb-saytlar, o'yinlar va mobil ilovalar yaratuvchi yosh dasturlash studiyasi.",
    "footer.navigation": "Navigatsiya",
    "footer.services": "Xizmatlar",
    "footer.connect": "Aloqa",
    "footer.rights": "Barcha huquqlar himoyalangan.",
    "footer.partOf": "Qismi",

    // Games Service Page
    "games.title": "O'yin",
    "games.title2": "Yaratish",
    "games.description": "Konsept-artdan yakuniy relizgacha — o'yin g'oyangizni hayotga tatbiq etamiz.",
    "games.startGame": "O'yinni boshlash",
    "games.playDemos": "Demo o'ynash",
    "games.interactiveDemo": "// Interaktiv demo - Navigatsiya uchun bosing",
    "games.whatWeCreate": "Biz nima yaratamiz",
    "games.whatWeCreateDesc": "// To'liq o'yin yaratish xizmatlari",
    "games.pcGames": "Kompyuter o'yinlari",
    "games.pcGamesDesc": "Windows, Mac va Linux uchun yuqori unumdor o'yinlar.",
    "games.mobileGames": "Mobil o'yinlar",
    "games.mobileGamesDesc": "iOS va Android uchun qiziqarli o'yinlar, sensorli boshqaruv uchun optimallashtirilgan.",
    "games.browserGames": "Brauzer o'yinlari",
    "games.browserGamesDesc": "WebGL va HTML5 o'yinlari, yuklab olmasdan to'g'ridan-to'g'ri brauzerda ishlaydi.",
    "games.3dDev": "3D Ishlab chiqish",
    "games.3dDevDesc": "Real fizika, yoritish va muhit bilan immersiv 3D olamlar.",
    "games.2dArt": "2D San'at va Animatsiya",
    "games.2dArtDesc": "Chiroyli 2D grafika, sprayt animatsiyalari va vizual effektlar.",
    "games.soundMusic": "Ovoz va Musiqa",
    "games.soundMusicDesc": "Original saundtreklar, ovoz effektlari va immersiv audio-dizayn.",
    "games.gameGenres": "O'yin janrlari",
    "games.gameGenresDesc": "// Barcha janrlarda ishlab chiqamiz",
    "games.techStack": "Texnologiyalar",
    "games.techStackDesc": "// Sanoat standartidagi vositalar va dvigatellar",
    "games.devProcess": "Ishlab chiqish jarayoni",
    "games.devProcessDesc": "// G'oyadan ishga tushirishgacha",
    "games.concept": "Konsept",
    "games.conceptDesc": "O'yin dizayni hujjati, syujet, mexanikani rejalashtirish",
    "games.prototype": "Prototip",
    "games.prototypeDesc": "Asosiy o'yin sikli, asosiy mexanikani sinovdan o'tkazish",
    "games.production": "Ishlab chiqarish",
    "games.productionDesc": "To'liq ishlab chiqish, san'at, ovoz, pardozlash",
    "games.launch": "Ishga tushirish",
    "games.launchDesc": "Sinov, optimallashtirish, reliz, qo'llab-quvvatlash",
    "games.readyTo": "Darajangizni",
    "games.levelUp": "oshirishga tayyormisiz?",
    "games.ctaDesc": "Keling, birga unutilmas o'yin tajribasini yarataylik.",
    "games.startProject": "Loyihani boshlash",
    "games.viewGames": "O'yinlarimiz",
    "games.action": "Jang",
    "games.adventure": "Sarguzasht",
    "games.rpg": "RPG",
    "games.puzzle": "Boshqotirma",
    "games.platformer": "Platformer",
    "games.shooter": "Otishma",
    "games.strategy": "Strategiya",
    "games.simulation": "Simulyator",
    "games.racing": "Poyga",
    "games.horror": "Qo'rqinchli",
    // Game Menu Demo
    "games.menu.mainMenu": "ASOSIY MENYU",
    "games.menu.selectMode": "REJIM TANLASH",
    "games.menu.settings": "SOZLAMALAR",
    "games.menu.language": "TIL",
    "games.menu.play": "O'YNASH",
    "games.menu.quit": "CHIQISH",
    "games.menu.singlePlayer": "YOLG'IZ O'YNASH",
    "games.menu.playWithFriends": "DO'STLAR BILAN",
    "games.menu.back": "ORQAGA",
    "games.menu.graphics": "GRAFIKA",
    "games.menu.audio": "OVOZ",
    "games.menu.controls": "BOSHQARUV",
    "games.menu.clickToSelect": "TANLASH UCHUN BOSING",

    // Web Development Service Page
    "web.title": "Veb",
    "web.title2": "Dasturlash",
    "web.description": "Kontseptsiyadan joylashtirishgacha — zamonaviy, kengaytiriladigan veb-yechimlar yaratamiz.",
    "web.startProject": "Loyihani boshlash",
    "web.viewWorks": "Ishlarimiz",
    "web.interactiveDemo": "// Interaktiv demo - Jonli ko'rish",
    "web.whatWeCreate": "Biz nima yaratamiz",
    "web.whatWeCreateDesc": "// To'liq veb-dasturlash xizmatlari",
    "web.landingPages": "Landing sahifalar",
    "web.landingPagesDesc": "Ajoyib dizayn va optimal ishlash bilan yuqori konversiyali landing sahifalar.",
    "web.webApps": "Veb-ilovalar",
    "web.webAppsDesc": "Boy funksionallik va uzluksiz UX bilan murakkab veb-ilovalar.",
    "web.ecommerce": "Elektron tijorat",
    "web.ecommerceDesc": "Xavfsiz to'lovlar, inventar boshqaruvi va tahlil bilan onlayn do'konlar.",
    "web.dashboards": "Boshqaruv panellari",
    "web.dashboardsDesc": "Real vaqt yangilanishlari va interaktiv grafiklar bilan ma'lumotlar vizualizatsiyasi panellari.",
    "web.apis": "API ishlab chiqish",
    "web.apisDesc": "Autentifikatsiya, cheklovlar va hujjatlar bilan RESTful va GraphQL API.",
    "web.cms": "CMS yechimlari",
    "web.cmsDesc": "Ehtiyojlaringizga moslashtirilgan maxsus kontent boshqaruv tizimlari.",
    "web.techStack": "Texnologiyalar",
    "web.techStackDesc": "// Biz ishlaydigan zamonaviy texnologiyalar",
    "web.frontend": "Frontend",
    "web.backend": "Backend",
    "web.database": "Ma'lumotlar bazasi",
    "web.devops": "DevOps",
    "web.devProcess": "Ishlab chiqish jarayoni",
    "web.devProcessDesc": "// G'oyadan ishga tushirishgacha",
    "web.discovery": "Kashfiyot",
    "web.discoveryDesc": "Talablarni yig'ish, foydalanuvchi tadqiqoti, loyiha doirasi",
    "web.design": "Dizayn",
    "web.designDesc": "Wireframe, UI/UX dizayn, prototiplash",
    "web.development": "Ishlab chiqish",
    "web.developmentDesc": "Frontend, backend, ma'lumotlar bazasi, sinovlar",
    "web.deployment": "Joylashtirish",
    "web.deploymentDesc": "Ishga tushirish, monitoring, qo'llab-quvvatlash",
    "web.readyTo": "Onlayn",
    "web.goOnline": "chiqishga tayyormisiz?",
    "web.ctaDesc": "Keling, raqamli mavjudligingizni birga yarataylik.",
    "web.startProjectBtn": "Loyihani boshlash",
    "web.viewPortfolio": "Portfolio",
    "web.features": "Asosiy xususiyatlar",
    "web.featuresDesc": "// Veb-saytlarimizni nima ajratib turadi",
    "web.responsive": "Moslashuvchan dizayn",
    "web.responsiveDesc": "Barcha qurilmalarda mukammal — kompyuter, planshet va mobil.",
    "web.seo": "SEO optimallashtirilgan",
    "web.seoDesc": "Qidiruv tizimlari uchun eng yaxshi amaliyotlar va tezkor yuklash bilan yaratilgan.",
    "web.secure": "Xavfsiz va ishonchli",
    "web.secureDesc": "SSL, autentifikatsiya va ma'lumotlar himoyasi bilan sanoat standartidagi xavfsizlik.",
    "web.scalable": "Kengaytiriladigan arxitektura",
    "web.scalableDesc": "Biznesingiz ehtiyojlari bilan birga o'sish uchun yaratilgan.",
    "web.fast": "Chaqmoq tezligida",
    "web.fastDesc": "Zamonaviy keshlash va CDN bilan optimallashtirilgan ishlash.",
    "web.accessible": "Qulay",
    "web.accessibleDesc": "Barcha imkoniyatlarga ega foydalanuvchilar uchun WCAG muvofiq.",

    // Mobile Development Service Page
    "mobile.title": "Mobil",
    "mobile.title2": "Dasturlash",
    "mobile.description": "Foydalanuvchilar yoqtiradigan mahalliy va kross-platforma ilovalari.",
    "mobile.startProject": "Ilovani boshlash",
    "mobile.viewApps": "Ilovalarimiz",
    "mobile.interactiveDemo": "// Interaktiv demo - Navigatsiya uchun suring",
    "mobile.whatWeCreate": "Biz nima yaratamiz",
    "mobile.whatWeCreateDesc": "// To'liq mobil dasturlash xizmatlari",
    "mobile.iosApps": "iOS ilovalari",
    "mobile.iosAppsDesc": "Apple ko'rsatmalari bo'yicha iPhone va iPad uchun mahalliy Swift ilovalari.",
    "mobile.androidApps": "Android ilovalari",
    "mobile.androidAppsDesc": "Butun Android ekotizimi uchun mahalliy Kotlin ilovalari.",
    "mobile.crossPlatform": "Kross-platforma",
    "mobile.crossPlatformDesc": "Bitta kod bazasidan ikkala platforma uchun React Native va Flutter ilovalari.",
    "mobile.appDesign": "Ilova UI/UX",
    "mobile.appDesignDesc": "Platforma ko'rsatmalariga muvofiq chiroyli, intuitiv interfeyslar.",
    "mobile.backend": "Backend va API",
    "mobile.backendDesc": "Kengaytiriladigan server infratuzilmasi va real vaqt sinxronizatsiyasi.",
    "mobile.maintenance": "Xizmat ko'rsatish",
    "mobile.maintenanceDesc": "Doimiy yangilanishlar, xatolarni tuzatish va optimallashtirish.",
    "mobile.techStack": "Texnologiyalar",
    "mobile.techStackDesc": "// Yetakchi mobil texnologiyalar",
    "mobile.ios": "iOS",
    "mobile.android": "Android",
    "mobile.crossPlatformTech": "Kross-platforma",
    "mobile.backendTech": "Backend",
    "mobile.devProcess": "Ishlab chiqish jarayoni",
    "mobile.devProcessDesc": "// Kontseptsiyadan App Store gacha",
    "mobile.ideation": "G'oya",
    "mobile.ideationDesc": "Bozor tadqiqoti, funksiyalarni rejalashtirish, texnik baholash",
    "mobile.design": "Dizayn",
    "mobile.designDesc": "Wireframe, prototiplar, UI/UX dizayn",
    "mobile.development": "Ishlab chiqish",
    "mobile.developmentDesc": "Mahalliy/kross-platforma dasturlash, API integratsiyasi",
    "mobile.launch": "Ishga tushirish",
    "mobile.launchDesc": "Sinovlar, App Store ga yuborish, qo'llab-quvvatlash",
    "mobile.readyTo": "Mobil",
    "mobile.goMobile": "bo'lishga tayyormisiz?",
    "mobile.ctaDesc": "Keling, ilova g'oyangizni hayotga tatbiq etaylik.",
    "mobile.startProjectBtn": "Loyihani boshlash",
    "mobile.viewPortfolio": "Portfolio",
    "mobile.features": "Ilova xususiyatlari",
    "mobile.featuresDesc": "// Ilovalarimizni nima ajratib turadi",
    "mobile.offline": "Oflayn rejim",
    "mobile.offlineDesc": "Internet aloqasisiz muammosiz ishlaydi.",
    "mobile.push": "Push-bildirishnomalar",
    "mobile.pushDesc": "Foydalanuvchilarni dolzarb bildirishnomalar bilan jalb qiling.",
    "mobile.analytics": "Tahlil",
    "mobile.analyticsDesc": "Foydalanuvchi xatti-harakatlarini va ilova samaradorligini kuzating.",
    "mobile.security": "Xavfsizlik",
    "mobile.securityDesc": "Shifrlangan ma'lumotlar, xavfsiz autentifikatsiya, maxfiylik.",
    "mobile.performance": "Yuqori samaradorlik",
    "mobile.performanceDesc": "Silliq 60fps animatsiyalar, tez yuklanish.",
    "mobile.updates": "OTA yangilanishlar",
    "mobile.updatesDesc": "App Store tekshiruvisiz yangilanishlar.",

    // UI/UX Design Service Page
    "design.title": "UI/UX",
    "design.title2": "Dizayn",
    "design.description": "Foydalanuvchilar yoqtiradigan chiroyli, intuitiv interfeyslar.",
    "design.startProject": "Dizaynni boshlash",
    "design.viewWorks": "Dizaynlarimiz",
    "design.interactiveDemo": "// Interaktiv demo - O'rganish uchun bosing",
    "design.whatWeCreate": "Biz nima yaratamiz",
    "design.whatWeCreateDesc": "// To'liq dizayn xizmatlari",
    "design.uiDesign": "UI Dizayn",
    "design.uiDesignDesc": "Zamonaviy estetika va detallarga e'tibor bilan piksel-mukammal interfeyslar.",
    "design.uxResearch": "UX Tadqiqotlar",
    "design.uxResearchDesc": "Auditoriyangizni tushunish uchun intervyular, so'rovnomalar va foydalanish testlari.",
    "design.wireframes": "Wireframe",
    "design.wireframesDesc": "Foydalanuvchi sayohatini vizualizatsiya qilish uchun wireframe.",
    "design.prototyping": "Prototiplash",
    "design.prototypingDesc": "Sinovlar va taqdimotlar uchun interaktiv prototiplar.",
    "design.designSystems": "Dizayn tizimlari",
    "design.designSystemsDesc": "Konsistentlik uchun kengaytiriladigan komponent kutubxonalari va qo'llanmalar.",
    "design.branding": "Brending",
    "design.brandingDesc": "Logotip dizayni, rang palitralari, tipografiya va brend identifikatsiyasi.",
    "design.tools": "Dizayn vositalari",
    "design.toolsDesc": "// Biz foydalanadigan professional dasturlar",
    "design.designTools": "Dizayn",
    "design.prototypeTools": "Prototiplash",
    "design.collaborationTools": "Hamkorlik",
    "design.devHandoff": "Dasturchilarga topshirish",
    "design.devProcess": "Dizayn jarayoni",
    "design.devProcessDesc": "// Tadqiqotdan topshirishgacha",
    "design.research": "Tadqiqot",
    "design.researchDesc": "UX tadqiqotlar, raqobatchi tahlili, talablarni yig'ish",
    "design.ideate": "G'oyalash",
    "design.ideateDesc": "Eskizlar, wireframe, axborot arxitekturasi",
    "design.designStep": "Dizayn",
    "design.designStepDesc": "Vizual dizayn, prototiplash, foydalanuvchi testlari",
    "design.handoff": "Topshirish",
    "design.handoffDesc": "Spetsifikatsiyalar, asset eksporti, amalga oshirish qo'llab-quvvatlashi",
    "design.readyTo": "Ajralib",
    "design.standOut": "turishga tayyormisiz?",
    "design.ctaDesc": "Keling, ta'sir qoldiruvchi dizaynlar yarataylik.",
    "design.startProjectBtn": "Loyihani boshlash",
    "design.viewPortfolio": "Portfolio",
    "design.features": "Dizayn tamoyillari",
    "design.featuresDesc": "// Qarorlarimizni nima yo'naltiradi",
    "design.userCentered": "Foydalanuvchiga yo'naltirilgan",
    "design.userCenteredDesc": "Har bir qaror foydalanuvchi ehtiyojlari va tadqiqotlar bilan asoslangan.",
    "design.accessible": "Qulay",
    "design.accessibleDesc": "Barcha imkoniyatlarga ega foydalanuvchilar uchun inklyuziv dizayn.",
    "design.consistent": "Konsistent",
    "design.consistentDesc": "Barcha aloqa nuqtalarida yagona vizual til.",
    "design.responsive": "Moslashuvchan",
    "design.responsiveDesc": "Har qanday ekran o'lchamida benuqson tajriba.",
    "design.delightful": "Hayratlanarli",
    "design.delightfulDesc": "Jalb qiluvchi mikro-interaksiyalar va animatsiyalar.",
    "design.scalable": "Kengaytiriladigan",
    "design.scalableDesc": "Mahsulot bilan birga o'sadigan dizayn tizimlari.",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("bi3-language") as Language;
    if (saved && ["en", "ru", "uz"].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("bi3-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
